# cargo-deny configuration: license, advisory, and source auditing for
# the dependency tree (which is deliberately tiny: rustc-hash only).

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
]

[advisories]
yanked = "deny"

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
